2018-12-19 15:16:47.442 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 18856 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 15:16:47.499 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 15:16:48.189 [main] o.m.spring.mapper.ClassPathMapperScanner:166 [WARN]: No MyBatis mapper was found in '[com.wangr.test]' package. Please check your configuration.
2018-12-19 15:16:49.514 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:90 [INFO]: Tomcat initialized with port(s): 8080 (http)
2018-12-19 15:16:49.565 [main] org.apache.catalina.core.StandardService:173 [INFO]: Starting service [Tomcat]
2018-12-19 15:16:49.566 [main] org.apache.catalina.core.StandardEngine:173 [INFO]: Starting Servlet Engine: Apache Tomcat/9.0.13
2018-12-19 15:16:49.573 [main] o.a.catalina.core.AprLifecycleListener:173 [INFO]: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\Program Files\Java\jdk1.8.0_181\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program Files\Java\jdk1.8.0_181\bin;D:\Program Files\Java\jdk1.8.0_181\jre\bin;D:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;D:\Program Files\TortoiseGit\bin;%MAVEN_HOME%\bin;E:\apache-maven-3.5.0\bin;C:\Users\wangr\AppData\Local\Microsoft\WindowsApps;;.]
2018-12-19 15:16:49.693 [main] o.a.c.c.C.[Tomcat].[localhost].[/]:173 [INFO]: Initializing Spring embedded WebApplicationContext
2018-12-19 15:16:49.693 [main] o.s.web.context.ContextLoader:296 [INFO]: Root WebApplicationContext: initialization completed in 2137 ms
2018-12-19 15:16:50.031 [main] o.s.s.concurrent.ThreadPoolTaskExecutor:171 [INFO]: Initializing ExecutorService 'applicationTaskExecutor'
2018-12-19 15:16:50.292 [main] c.a.d.s.b.a.DruidDataSourceAutoConfigure:56 [INFO]: Init DruidDataSource
2018-12-19 15:16:50.425 [main] com.alibaba.druid.pool.DruidDataSource:930 [INFO]: {dataSource-1} inited
2018-12-19 15:16:50.813 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:50.817 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:51.322 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:51.826 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:52.329 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:52.834 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:53.337 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:53.842 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:54.347 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:54.849 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:55.353 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:55.858 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:56.360 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:16:56.865 [Druid-ConnectionPool-Create-1020421154] com.alibaba.druid.pool.DruidDataSource:2471 [ERROR]: create connection SQLException, url: jdbc:mysql://localhost:3306/hlms_suite?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true, errorCode 1049, state 42000
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'hlms_suite'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
2018-12-19 15:17:38.694 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 9920 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 15:17:38.700 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 15:17:39.422 [main] o.m.spring.mapper.ClassPathMapperScanner:166 [WARN]: No MyBatis mapper was found in '[com.wangr.test]' package. Please check your configuration.
2018-12-19 15:17:40.087 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:90 [INFO]: Tomcat initialized with port(s): 8080 (http)
2018-12-19 15:17:40.114 [main] org.apache.catalina.core.StandardService:173 [INFO]: Starting service [Tomcat]
2018-12-19 15:17:40.115 [main] org.apache.catalina.core.StandardEngine:173 [INFO]: Starting Servlet Engine: Apache Tomcat/9.0.13
2018-12-19 15:17:40.122 [main] o.a.catalina.core.AprLifecycleListener:173 [INFO]: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\Program Files\Java\jdk1.8.0_181\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program Files\Java\jdk1.8.0_181\bin;D:\Program Files\Java\jdk1.8.0_181\jre\bin;D:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;D:\Program Files\TortoiseGit\bin;%MAVEN_HOME%\bin;E:\apache-maven-3.5.0\bin;C:\Users\wangr\AppData\Local\Microsoft\WindowsApps;;.]
2018-12-19 15:17:40.221 [main] o.a.c.c.C.[Tomcat].[localhost].[/]:173 [INFO]: Initializing Spring embedded WebApplicationContext
2018-12-19 15:17:40.222 [main] o.s.web.context.ContextLoader:296 [INFO]: Root WebApplicationContext: initialization completed in 1466 ms
2018-12-19 15:17:40.515 [main] o.s.s.concurrent.ThreadPoolTaskExecutor:171 [INFO]: Initializing ExecutorService 'applicationTaskExecutor'
2018-12-19 15:17:40.660 [main] c.a.d.s.b.a.DruidDataSourceAutoConfigure:56 [INFO]: Init DruidDataSource
2018-12-19 15:17:40.815 [main] com.alibaba.druid.pool.DruidDataSource:930 [INFO]: {dataSource-1} inited
2018-12-19 15:17:41.289 [main] org.quartz.impl.StdSchedulerFactory:1208 [INFO]: Using default implementation for ThreadExecutor
2018-12-19 15:17:41.324 [main] org.quartz.core.SchedulerSignalerImpl:61 [INFO]: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2018-12-19 15:17:41.324 [main] org.quartz.core.QuartzScheduler:229 [INFO]: Quartz Scheduler v.2.3.0 created.
2018-12-19 15:17:41.325 [main] org.quartz.simpl.RAMJobStore:155 [INFO]: RAMJobStore initialized.
2018-12-19 15:17:41.326 [main] org.quartz.core.QuartzScheduler:294 [INFO]: Scheduler meta-data: Quartz Scheduler (v2.3.0) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2018-12-19 15:17:41.326 [main] org.quartz.impl.StdSchedulerFactory:1362 [INFO]: Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
2018-12-19 15:17:41.326 [main] org.quartz.impl.StdSchedulerFactory:1366 [INFO]: Quartz scheduler version: 2.3.0
2018-12-19 15:17:41.326 [main] org.quartz.core.QuartzScheduler:2287 [INFO]: JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@6002e944
2018-12-19 15:17:41.336 [main] o.s.s.concurrent.ThreadPoolTaskScheduler:171 [INFO]: Initializing ExecutorService 'taskScheduler'
2018-12-19 15:17:41.390 [main] o.s.s.quartz.SchedulerFactoryBean:726 [INFO]: Starting Quartz Scheduler now
2018-12-19 15:17:41.391 [main] org.quartz.core.QuartzScheduler:547 [INFO]: Scheduler quartzScheduler_$_NON_CLUSTERED started.
2018-12-19 15:17:41.431 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:204 [INFO]: Tomcat started on port(s): 8080 (http) with context path ''
2018-12-19 15:17:41.435 [main] com.wangr.test.TestApplication:59 [INFO]: Started TestApplication in 3.374 seconds (JVM running for 4.281)
2018-12-19 16:19:45.160 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 20312 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:19:45.188 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:19:46.087 [main] o.m.spring.mapper.ClassPathMapperScanner:166 [WARN]: No MyBatis mapper was found in '[com.wangr.test]' package. Please check your configuration.
2018-12-19 16:19:46.145 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:19:46.155 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:19:46.158 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:26:55.345 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 18460 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:26:55.348 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:26:56.144 [main] o.m.spring.mapper.ClassPathMapperScanner:166 [WARN]: No MyBatis mapper was found in '[com.wangr.test]' package. Please check your configuration.
2018-12-19 16:26:56.814 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:90 [INFO]: Tomcat initialized with port(s): 8080 (http)
2018-12-19 16:26:56.838 [main] org.apache.catalina.core.StandardService:173 [INFO]: Starting service [Tomcat]
2018-12-19 16:26:56.839 [main] org.apache.catalina.core.StandardEngine:173 [INFO]: Starting Servlet Engine: Apache Tomcat/9.0.13
2018-12-19 16:26:56.846 [main] o.a.catalina.core.AprLifecycleListener:173 [INFO]: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\Program Files\Java\jdk1.8.0_181\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program Files\Java\jdk1.8.0_181\bin;D:\Program Files\Java\jdk1.8.0_181\jre\bin;D:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;D:\Program Files\TortoiseGit\bin;%MAVEN_HOME%\bin;E:\apache-maven-3.5.0\bin;C:\Users\wangr\AppData\Local\Microsoft\WindowsApps;;.]
2018-12-19 16:26:56.936 [main] o.a.c.c.C.[Tomcat].[localhost].[/]:173 [INFO]: Initializing Spring embedded WebApplicationContext
2018-12-19 16:26:56.937 [main] o.s.web.context.ContextLoader:296 [INFO]: Root WebApplicationContext: initialization completed in 1476 ms
2018-12-19 16:26:57.029 [main] c.a.d.s.b.a.DruidDataSourceAutoConfigure:56 [INFO]: Init DruidDataSource
2018-12-19 16:26:57.178 [main] com.alibaba.druid.pool.DruidDataSource:930 [INFO]: {dataSource-1} inited
2018-12-19 16:26:57.462 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'scheduleJobInitListener': Unsatisfied dependency expressed through field 'scheduler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'quartzScheduler': Unsatisfied dependency expressed through field 'scheduler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'quartzConfigration': Unsatisfied dependency expressed through field 'jobFactory'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.quartz.spi.JobFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2018-12-19 16:26:57.465 [main] com.alibaba.druid.pool.DruidDataSource:1825 [INFO]: {dataSource-1} closed
2018-12-19 16:26:57.468 [main] org.apache.catalina.core.StandardService:173 [INFO]: Stopping service [Tomcat]
2018-12-19 16:26:57.583 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:26:57.774 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field jobFactory in com.wangr.test.quartz.config.QuartzConfigration required a bean of type 'org.quartz.spi.JobFactory' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'org.quartz.spi.JobFactory' in your configuration.

2018-12-19 16:28:12.022 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 18248 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:28:12.083 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:28:12.911 [main] o.m.spring.mapper.ClassPathMapperScanner:166 [WARN]: No MyBatis mapper was found in '[com.wangr.test]' package. Please check your configuration.
2018-12-19 16:28:13.759 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:90 [INFO]: Tomcat initialized with port(s): 8080 (http)
2018-12-19 16:28:13.784 [main] org.apache.catalina.core.StandardService:173 [INFO]: Starting service [Tomcat]
2018-12-19 16:28:13.784 [main] org.apache.catalina.core.StandardEngine:173 [INFO]: Starting Servlet Engine: Apache Tomcat/9.0.13
2018-12-19 16:28:13.794 [main] o.a.catalina.core.AprLifecycleListener:173 [INFO]: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\Program Files\Java\jdk1.8.0_181\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program Files\Java\jdk1.8.0_181\bin;D:\Program Files\Java\jdk1.8.0_181\jre\bin;D:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;D:\Program Files\TortoiseGit\bin;%MAVEN_HOME%\bin;E:\apache-maven-3.5.0\bin;C:\Users\wangr\AppData\Local\Microsoft\WindowsApps;;.]
2018-12-19 16:28:13.901 [main] o.a.c.c.C.[Tomcat].[localhost].[/]:173 [INFO]: Initializing Spring embedded WebApplicationContext
2018-12-19 16:28:13.901 [main] o.s.web.context.ContextLoader:296 [INFO]: Root WebApplicationContext: initialization completed in 1735 ms
2018-12-19 16:28:13.994 [main] c.a.d.s.b.a.DruidDataSourceAutoConfigure:56 [INFO]: Init DruidDataSource
2018-12-19 16:28:14.146 [main] com.alibaba.druid.pool.DruidDataSource:930 [INFO]: {dataSource-1} inited
2018-12-19 16:28:14.434 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'scheduleJobInitListener': Unsatisfied dependency expressed through field 'scheduler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'quartzScheduler': Unsatisfied dependency expressed through field 'scheduler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'quartzConfigration': Unsatisfied dependency expressed through field 'jobFactory'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.quartz.spi.JobFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2018-12-19 16:28:14.437 [main] com.alibaba.druid.pool.DruidDataSource:1825 [INFO]: {dataSource-1} closed
2018-12-19 16:28:14.440 [main] org.apache.catalina.core.StandardService:173 [INFO]: Stopping service [Tomcat]
2018-12-19 16:28:14.452 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:28:14.569 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field jobFactory in com.wangr.test.quartz.config.QuartzConfigration required a bean of type 'org.quartz.spi.JobFactory' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'org.quartz.spi.JobFactory' in your configuration.

2018-12-19 16:29:25.287 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 16788 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:29:25.291 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:29:26.757 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:90 [INFO]: Tomcat initialized with port(s): 8080 (http)
2018-12-19 16:29:26.784 [main] org.apache.catalina.core.StandardService:173 [INFO]: Starting service [Tomcat]
2018-12-19 16:29:26.784 [main] org.apache.catalina.core.StandardEngine:173 [INFO]: Starting Servlet Engine: Apache Tomcat/9.0.13
2018-12-19 16:29:26.790 [main] o.a.catalina.core.AprLifecycleListener:173 [INFO]: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\Program Files\Java\jdk1.8.0_181\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program Files\Java\jdk1.8.0_181\bin;D:\Program Files\Java\jdk1.8.0_181\jre\bin;D:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;D:\Program Files\TortoiseGit\bin;%MAVEN_HOME%\bin;E:\apache-maven-3.5.0\bin;C:\Users\wangr\AppData\Local\Microsoft\WindowsApps;;.]
2018-12-19 16:29:26.881 [main] o.a.c.c.C.[Tomcat].[localhost].[/]:173 [INFO]: Initializing Spring embedded WebApplicationContext
2018-12-19 16:29:26.882 [main] o.s.web.context.ContextLoader:296 [INFO]: Root WebApplicationContext: initialization completed in 1429 ms
2018-12-19 16:29:26.985 [main] c.a.d.s.b.a.DruidDataSourceAutoConfigure:56 [INFO]: Init DruidDataSource
2018-12-19 16:29:27.134 [main] com.alibaba.druid.pool.DruidDataSource:930 [INFO]: {dataSource-1} inited
2018-12-19 16:29:27.417 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'scheduleJobInitListener': Unsatisfied dependency expressed through field 'scheduler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'quartzScheduler': Unsatisfied dependency expressed through field 'scheduler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'quartzConfigration': Unsatisfied dependency expressed through field 'jobFactory'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.quartz.spi.JobFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
2018-12-19 16:29:27.420 [main] com.alibaba.druid.pool.DruidDataSource:1825 [INFO]: {dataSource-1} closed
2018-12-19 16:29:27.423 [main] org.apache.catalina.core.StandardService:173 [INFO]: Stopping service [Tomcat]
2018-12-19 16:29:27.434 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:29:27.558 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field jobFactory in com.wangr.test.quartz.config.QuartzConfigration required a bean of type 'org.quartz.spi.JobFactory' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'org.quartz.spi.JobFactory' in your configuration.

2018-12-19 16:32:50.509 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 3240 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:32:50.516 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:32:51.535 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:32:51.545 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:32:51.550 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:33:19.169 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 7112 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:33:19.173 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:33:19.973 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:33:19.982 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:33:19.985 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:33:50.921 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 8836 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:33:50.926 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:33:51.980 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:33:51.989 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:33:51.991 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:34:05.538 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 15584 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:34:05.543 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:34:06.381 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:34:06.391 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:34:06.395 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:39:22.959 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 12044 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:39:22.963 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:39:24.286 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:39:24.295 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:39:24.299 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:40:08.734 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 19752 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:40:08.745 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:40:09.897 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:40:09.909 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:40:09.912 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:43:55.086 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 12456 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:43:55.090 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:43:55.963 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:43:55.973 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:43:55.976 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:46:40.175 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 4640 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:46:40.192 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:46:41.028 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:46:41.039 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:46:41.042 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:47:18.033 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 16400 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:47:18.037 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:47:18.945 [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext:554 [WARN]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration; factoryMethodName=quartzScheduler; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]] for bean 'quartzScheduler': There is already [Generic bean: class [com.wangr.test.quartz.schedule.QuartzScheduler]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class]] bound.
2018-12-19 16:47:18.956 [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener:142 [INFO]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-12-19 16:47:18.959 [main] o.s.b.d.LoggingFailureAnalysisReporter:42 [ERROR]: 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'quartzScheduler', defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class], could not be registered. A bean with that name has already been defined in file [E:\CODE\test\target\classes\com\wangr\test\quartz\schedule\QuartzScheduler.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

2018-12-19 16:47:49.081 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 9228 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:47:49.086 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:47:50.945 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:90 [INFO]: Tomcat initialized with port(s): 8080 (http)
2018-12-19 16:47:50.969 [main] org.apache.catalina.core.StandardService:173 [INFO]: Starting service [Tomcat]
2018-12-19 16:47:50.969 [main] org.apache.catalina.core.StandardEngine:173 [INFO]: Starting Servlet Engine: Apache Tomcat/9.0.13
2018-12-19 16:47:50.976 [main] o.a.catalina.core.AprLifecycleListener:173 [INFO]: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\Program Files\Java\jdk1.8.0_181\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program Files\Java\jdk1.8.0_181\bin;D:\Program Files\Java\jdk1.8.0_181\jre\bin;D:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;D:\Program Files\TortoiseGit\bin;%MAVEN_HOME%\bin;E:\apache-maven-3.5.0\bin;C:\Users\wangr\AppData\Local\Microsoft\WindowsApps;;.]
2018-12-19 16:47:51.071 [main] o.a.c.c.C.[Tomcat].[localhost].[/]:173 [INFO]: Initializing Spring embedded WebApplicationContext
2018-12-19 16:47:51.072 [main] o.s.web.context.ContextLoader:296 [INFO]: Root WebApplicationContext: initialization completed in 1893 ms
2018-12-19 16:47:51.159 [main] c.a.d.s.b.a.DruidDataSourceAutoConfigure:56 [INFO]: Init DruidDataSource
2018-12-19 16:47:51.306 [main] com.alibaba.druid.pool.DruidDataSource:930 [INFO]: {dataSource-1} inited
2018-12-19 16:47:51.735 [main] org.quartz.impl.StdSchedulerFactory:1208 [INFO]: Using default implementation for ThreadExecutor
2018-12-19 16:47:51.737 [main] org.quartz.simpl.SimpleThreadPool:268 [INFO]: Job execution threads will use class loader of thread: main
2018-12-19 16:47:51.750 [main] org.quartz.core.SchedulerSignalerImpl:61 [INFO]: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2018-12-19 16:47:51.751 [main] org.quartz.core.QuartzScheduler:229 [INFO]: Quartz Scheduler v.2.3.0 created.
2018-12-19 16:47:51.752 [main] org.quartz.simpl.RAMJobStore:155 [INFO]: RAMJobStore initialized.
2018-12-19 16:47:51.753 [main] org.quartz.core.QuartzScheduler:294 [INFO]: Scheduler meta-data: Quartz Scheduler (v2.3.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2018-12-19 16:47:51.754 [main] org.quartz.impl.StdSchedulerFactory:1362 [INFO]: Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2018-12-19 16:47:51.754 [main] org.quartz.impl.StdSchedulerFactory:1366 [INFO]: Quartz scheduler version: 2.3.0
2018-12-19 16:47:52.076 [main] o.s.s.concurrent.ThreadPoolTaskExecutor:171 [INFO]: Initializing ExecutorService 'applicationTaskExecutor'
2018-12-19 16:47:52.263 [main] org.quartz.impl.StdSchedulerFactory:1208 [INFO]: Using default implementation for ThreadExecutor
2018-12-19 16:47:52.264 [main] org.quartz.core.SchedulerSignalerImpl:61 [INFO]: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2018-12-19 16:47:52.264 [main] org.quartz.core.QuartzScheduler:229 [INFO]: Quartz Scheduler v.2.3.0 created.
2018-12-19 16:47:52.265 [main] org.quartz.simpl.RAMJobStore:155 [INFO]: RAMJobStore initialized.
2018-12-19 16:47:52.265 [main] org.quartz.core.QuartzScheduler:294 [INFO]: Scheduler meta-data: Quartz Scheduler (v2.3.0) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2018-12-19 16:47:52.265 [main] org.quartz.impl.StdSchedulerFactory:1362 [INFO]: Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
2018-12-19 16:47:52.265 [main] org.quartz.impl.StdSchedulerFactory:1366 [INFO]: Quartz scheduler version: 2.3.0
2018-12-19 16:47:52.265 [main] org.quartz.core.QuartzScheduler:2287 [INFO]: JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@47acd13b
2018-12-19 16:47:52.275 [main] o.s.s.concurrent.ThreadPoolTaskScheduler:171 [INFO]: Initializing ExecutorService 'taskScheduler'
2018-12-19 16:47:52.340 [main] o.s.s.quartz.SchedulerFactoryBean:726 [INFO]: Starting Quartz Scheduler now
2018-12-19 16:47:52.341 [main] org.quartz.core.QuartzScheduler:547 [INFO]: Scheduler quartzScheduler_$_NON_CLUSTERED started.
2018-12-19 16:47:55.635 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:204 [INFO]: Tomcat started on port(s): 8080 (http) with context path ''
2018-12-19 16:47:55.639 [main] com.wangr.test.TestApplication:59 [INFO]: Started TestApplication in 7.278 seconds (JVM running for 8.201)
2018-12-19 16:50:00.616 [main] com.wangr.test.TestApplication:50 [INFO]: Starting TestApplication on DESKTOP-QRJUJBD with PID 17224 (E:\CODE\test\target\classes started by wangr in E:\CODE\test)
2018-12-19 16:50:00.621 [main] com.wangr.test.TestApplication:675 [INFO]: No active profile set, falling back to default profiles: default
2018-12-19 16:50:02.108 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:90 [INFO]: Tomcat initialized with port(s): 8080 (http)
2018-12-19 16:50:02.133 [main] org.apache.catalina.core.StandardService:173 [INFO]: Starting service [Tomcat]
2018-12-19 16:50:02.133 [main] org.apache.catalina.core.StandardEngine:173 [INFO]: Starting Servlet Engine: Apache Tomcat/9.0.13
2018-12-19 16:50:02.142 [main] o.a.catalina.core.AprLifecycleListener:173 [INFO]: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [D:\Program Files\Java\jdk1.8.0_181\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Program Files\Java\jdk1.8.0_181\bin;D:\Program Files\Java\jdk1.8.0_181\jre\bin;D:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;D:\Program Files\TortoiseGit\bin;%MAVEN_HOME%\bin;E:\apache-maven-3.5.0\bin;C:\Users\wangr\AppData\Local\Microsoft\WindowsApps;;.]
2018-12-19 16:50:02.233 [main] o.a.c.c.C.[Tomcat].[localhost].[/]:173 [INFO]: Initializing Spring embedded WebApplicationContext
2018-12-19 16:50:02.233 [main] o.s.web.context.ContextLoader:296 [INFO]: Root WebApplicationContext: initialization completed in 1520 ms
2018-12-19 16:50:02.319 [main] c.a.d.s.b.a.DruidDataSourceAutoConfigure:56 [INFO]: Init DruidDataSource
2018-12-19 16:50:02.469 [main] com.alibaba.druid.pool.DruidDataSource:930 [INFO]: {dataSource-1} inited
2018-12-19 16:50:02.769 [main] org.quartz.impl.StdSchedulerFactory:1208 [INFO]: Using default implementation for ThreadExecutor
2018-12-19 16:50:02.772 [main] org.quartz.simpl.SimpleThreadPool:268 [INFO]: Job execution threads will use class loader of thread: main
2018-12-19 16:50:02.783 [main] org.quartz.core.SchedulerSignalerImpl:61 [INFO]: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2018-12-19 16:50:02.784 [main] org.quartz.core.QuartzScheduler:229 [INFO]: Quartz Scheduler v.2.3.0 created.
2018-12-19 16:50:02.785 [main] org.quartz.simpl.RAMJobStore:155 [INFO]: RAMJobStore initialized.
2018-12-19 16:50:02.786 [main] org.quartz.core.QuartzScheduler:294 [INFO]: Scheduler meta-data: Quartz Scheduler (v2.3.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2018-12-19 16:50:02.787 [main] org.quartz.impl.StdSchedulerFactory:1362 [INFO]: Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2018-12-19 16:50:02.787 [main] org.quartz.impl.StdSchedulerFactory:1366 [INFO]: Quartz scheduler version: 2.3.0
2018-12-19 16:50:03.107 [main] o.s.s.concurrent.ThreadPoolTaskExecutor:171 [INFO]: Initializing ExecutorService 'applicationTaskExecutor'
2018-12-19 16:50:03.287 [main] org.quartz.impl.StdSchedulerFactory:1208 [INFO]: Using default implementation for ThreadExecutor
2018-12-19 16:50:03.289 [main] org.quartz.core.SchedulerSignalerImpl:61 [INFO]: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2018-12-19 16:50:03.289 [main] org.quartz.core.QuartzScheduler:229 [INFO]: Quartz Scheduler v.2.3.0 created.
2018-12-19 16:50:03.289 [main] org.quartz.simpl.RAMJobStore:155 [INFO]: RAMJobStore initialized.
2018-12-19 16:50:03.289 [main] org.quartz.core.QuartzScheduler:294 [INFO]: Scheduler meta-data: Quartz Scheduler (v2.3.0) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2018-12-19 16:50:03.289 [main] org.quartz.impl.StdSchedulerFactory:1362 [INFO]: Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
2018-12-19 16:50:03.290 [main] org.quartz.impl.StdSchedulerFactory:1366 [INFO]: Quartz scheduler version: 2.3.0
2018-12-19 16:50:03.291 [main] org.quartz.core.QuartzScheduler:2287 [INFO]: JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@5eb5da12
2018-12-19 16:50:03.299 [main] o.s.s.concurrent.ThreadPoolTaskScheduler:171 [INFO]: Initializing ExecutorService 'taskScheduler'
2018-12-19 16:50:03.379 [main] o.s.s.quartz.SchedulerFactoryBean:726 [INFO]: Starting Quartz Scheduler now
2018-12-19 16:50:03.379 [main] org.quartz.core.QuartzScheduler:547 [INFO]: Scheduler quartzScheduler_$_NON_CLUSTERED started.
2018-12-19 16:50:03.402 [main] org.quartz.core.QuartzScheduler:547 [INFO]: Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2018-12-19 16:50:03.455 [main] o.s.b.w.embedded.tomcat.TomcatWebServer:204 [INFO]: Tomcat started on port(s): 8080 (http) with context path ''
2018-12-19 16:50:03.459 [main] com.wangr.test.TestApplication:59 [INFO]: Started TestApplication in 3.795 seconds (JVM running for 4.714)
